---

- name: Installing logstash configuration file
  sudo: true
  template: src=logstash.conf.j2 dest="{{ logstash_conf_dir }}/cassandra.conf" owner=root group=root mode=0644
  notify:
    - restart logstash
